### ISSUE TITLE
write library for cor file validation

### ISSUE THREAD

**Issue by fica99** [fica99/Corewar#5]
Необходимо написать функции для получения следующих данных из .cor файла:
- уникальный идентификационный номер
- имя чемпиона
- комментарий чемпиона
- размер исполняемого кода в байтах
- исполняемый код

Функции также должны определять является ли файл валидным или нет.
В случае не корректности, надо иметь возможность определить в чем ошибка.

Функции должны быть универсальными для дизассемблера и для виртуальной машины.
Можно это все сделать ввиду отдельной библиотеки.

Виртуальная машина читает полученные файлы с байт-кодом чемпионов и проверяет их на наличие magic header'а, соответствие указанного размера кода реальному и так далее.

Кстати, если программа-транслятор не придавала значения максимальному размеру исполняемого кода, то для виртуальной машины этот параметр имеет значение и не может превышать 682 байта, однако для дизассемблера это не играет роли:
```
# define MEM_SIZE           (4 * 1024)
// ...
# define CHAMP_MAX_SIZE     (MEM_SIZE / 6)
```
Минимального ограничения на размер исполняемого кода у виртуальной машины нет, поэтому он может отсутствовать полностью.

Подробное описание в Wiki.

Добавить краткое описание функций и их прототипы в wiki.

**Comment by mmarti42** [comment]
`t_champ *validate_and_parse(char *filename);`

`#include "disasm.h"`

библиотека libasm

Функция валидирует и парсит _.cor_ файл. В случае ошибки возвращает _NULL_ и печатает сообщение в стандартный поток ошибок. 

Принимает имя файла.

Возвращает указатель на структуру t_champ

`typedef struct  s_champ`
{
	`unsigned		id;  // идентификационный номер `
	`unsigned char 	*name; // имя чемпиона  `
	`unsigned char	*comment;  // комментарий чемпиона  `
	`size_t			exec_code_size;  // размер исполняемого кода в байтах  `
	`t_op   *exec_code;  // список команд и аргументов  `

}`t_champ;`

**ПОЛЕ id ОСТАЕТСЯ НЕЗАПОЛНЕННЫМ Т.К. ИДЕНТИФИКАЦИОННЫЙ НОМЕР ПРИСВАИВАЕТСЯ ВИРТУАЛЬНОЙ МАШИНОЙ ВО ВРЕМЯ ПАРСИНГА АРГУМЕНТОВ**

**Comment by mmarti42** [comment]
Содержимое структу **t_op_list**:  
`typedef struct			s_op_list`
`{`
`	t_op				operation; // Вся информация об операции`
`	int 				args_val[3]; // Значения аргументов операции`
`	struct s_op_list	*next; // Указатель на след операцию`
`}						t_op_list;`

**Comment by mmarti42** [comment]
Содержимое структуры **t_op**:  
`typedef struct	s_op`
`{`
`	char		*name; // Имя операции`
`	uint8_t		code; // Код операции`
`	uint8_t		args_num; // Количество аргументов`
`	t_bool		args_types_code; // Есть ли байт типов аргументов`
`	uint8_t		args_types[3]; // Типы аргументов (T_IND, T_REG, T_DIR)`
`	uint8_t		t_dir_size; // размер аргумента T_DIR`
`	int32_t 		args_val[3]; // Значения аргументов операции`  
`	struct s_op	*next; // Указатель на след операцию`  
`}				t_op;`

**Comment by mmarti42** [comment]
Функция ‘void free_champ(t_champ *ch)’  

Фришит структуру чемпиона
